services:
  - type: web
    name: code-runner
    runtime: python
    plan: free
    region: oregon
    branch: master
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 30"
    healthCheckPath: /
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9